insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (1, 'Jesse Dorn', 4, 30);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (2, 'Jake Nash', 8, 127);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (3, 'Whoopi Jonze', 5, 48);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (4, 'Johnnie Mitra', 8, 130);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (5, 'Collin Coyote', 7, 129);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (6, 'Lari Sevenfold', 7, 127);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (7, 'Franco Macy', 4, 99);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (8, 'Rosanne Speaks', 12, 88);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (9, 'Ralph Rhys-Davies', 5, 104);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (10, 'Mel Hayes', 4, 108);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (11, 'Curt Hewitt', 11, 68);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (12, 'Javon Webb', 11, 30);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (13, 'Ronny Fonda', 7, 145);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (14, 'Al Easton', 7, 39);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (15, 'Brenda Strong', 9, 73);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (16, 'Cheryl Craddock', 5, 59);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (17, 'Phil Berkeley', 12, 117);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (18, 'Keith Coward', 15, 122);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (19, 'April Tankard', 9, 83);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (20, 'Rene Hartnett', 3, 142);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (21, 'Jean Levert', 11, 34);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (22, 'Elias Coleman', 3, 57);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (23, 'Jaime Stuermer', 7, 37);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (24, 'Natasha Gough', 15, 103);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (25, 'Sheryl Thomas', 5, 55);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (26, 'Gilberto Vincent', 7, 124);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (27, 'Kurtwood Deejay', 5, 72);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (28, 'Laura Gore', 11, 102);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (29, 'Taylor McLachlan', 5, 114);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (30, 'Janice Hall', 9, 89);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (31, 'Janeane Phillippe', 6, 34);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (32, 'Wes Lange', 9, 143);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (33, 'Teri Morales', 7, 150);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (34, 'Kevn Wakeling', 12, 39);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (35, 'Joey Sweeney', 14, 76);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (36, 'Franco Culkin', 4, 65);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (37, 'John Addy', 14, 103);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (38, 'Meredith Ceasar', 13, 138);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (39, 'Brad Moriarty', 10, 44);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (40, 'Christine Nicholson', 15, 139);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (41, 'Ali Donelly', 4, 148);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (42, 'Kathleen Tolkan', 9, 129);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (43, 'Judi Keener', 9, 78);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (44, 'Diamond Colin Young', 7, 94);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (45, 'Mel Sandler', 3, 82);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (46, 'Colin Bryson', 4, 57);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (47, 'Devon Boone', 6, 113);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (48, 'Trick Rains', 13, 79);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (49, 'Mekhi Horizon', 9, 42);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (50, 'Saffron Trejo', 14, 141);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (51, 'Bernard Polley', 10, 123);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (52, 'Brenda Griggs', 15, 45);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (53, 'Fiona Phillippe', 4, 135);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (54, 'Harvey Fiennes', 9, 35);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (55, 'Kathleen Moriarty', 15, 105);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (56, 'Marc May', 15, 106);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (57, 'Laurence Hurley', 14, 67);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (58, 'Charles Iglesias', 4, 38);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (59, 'Kurt Levine', 8, 77);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (60, 'Curt Schreiber', 12, 46);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (61, 'Meredith Bloch', 14, 106);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (62, 'Matthew Chestnut', 14, 110);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (63, 'Gina Wilkinson', 5, 68);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (64, 'Andrea Stuermer', 15, 34);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (65, 'Shawn Crudup', 13, 99);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (66, 'Carole Goldberg', 9, 115);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (67, 'William Thornton', 5, 111);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (68, 'Joanna Hersh', 6, 137);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (69, 'Cuba Turner', 3, 81);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (70, 'Jean-Luc Kershaw', 6, 50);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (71, 'Balthazar Wheel', 3, 113);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (72, 'Michelle Diesel', 10, 68);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (73, 'Alicia Flanagan', 15, 135);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (74, 'Laurie Tomei', 5, 37);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (75, 'Irene Avalon', 8, 93);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (76, 'Glen Wagner', 5, 148);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (77, 'Rod Stevenson', 13, 30);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (78, 'Glen Karyo', 8, 78);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (79, 'Reese McElhone', 5, 50);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (80, 'Juliet Clarkson', 4, 86);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (81, 'Richard Watson', 6, 54);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (82, 'Elle Rifkin', 6, 44);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (83, 'Lila Damon', 10, 78);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (84, 'Trey Burke', 15, 62);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (85, 'Mindy Culkin', 7, 43);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (86, 'Allison Posey', 7, 149);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (87, 'Jesse Winans', 7, 115);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (88, 'Chi Adams', 8, 116);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (89, 'Elias Young', 14, 98);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (90, 'Derrick Watley', 13, 103);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (91, 'Bob Ticotin', 13, 58);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (92, 'Sophie Kinney', 6, 138);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (93, 'Elizabeth Spacek', 5, 93);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (94, 'Cole Del Toro', 12, 66);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (95, 'Russell Hayek', 10, 120);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (96, 'Rosario Baranski', 11, 101);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (97, 'Sissy Turner', 3, 30);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (98, 'Jesse Tomei', 14, 37);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (99, 'Illeana Paquin', 15, 91);

insert into SYSTEM.WRITER (WRITERID, WRITERNAME, NUMYEARSOFEXPERIENCE, PAYPERHOUR)
values (100, 'Hank Levert', 7, 58);

commit;

